"""
download_everyday_conversations.py — fetch HuggingFaceTB/everyday-conversations-llama3.1-2k,
convert to engram's User:/Bot: corpus format, write to corpus/everyday_conversations.txt.

This dataset is 2.18 MB / 2.4k rows / ~470K tokens / Apache-2.0,
generated by Llama-3.1-70B for training tiny LMs on simple greetings,
assistant identity awareness, and ~20 everyday topics. Already clean
(no numeric ID artifacts), so no need to run corpus_clean.py on it.

Run from repo root:
    uv run download_everyday_conversations.py
"""

import os
import re

OUTPUT = "corpus/everyday_conversations.txt"


def main():
    from datasets import load_dataset

    print("Loading HuggingFaceTB/everyday-conversations-llama3.1-2k …")
    # Use the train_sft split (2.26k rows); skip test_sft (119 rows).
    ds = load_dataset("HuggingFaceTB/everyday-conversations-llama3.1-2k", split="train_sft")
    print(f"  Loaded {len(ds)} conversations")

    n_lines = 0
    n_chars = 0
    with open(OUTPUT, "w", encoding="utf-8") as f:
        for row in ds:
            messages = row["messages"]
            for msg in messages:
                role = msg["role"]
                content = msg["content"].strip()
                if not content:
                    continue
                # Map roles to engram's expected speaker tags.
                tag = "User:" if role == "user" else "Bot:"
                # Lowercase + light cleanup to match dailydialog_clean.txt format.
                content = content.lower()
                # Replace digit-runs with <num> placeholder.
                content = re.sub(r"\d+", "<num>", content)
                # Drop tokens with mixed alphanum garbage.
                tokens = []
                for tok in re.findall(r"<num>|[^\w\s<>]|[a-z]+", content):
                    if tok in ("<num>",) or re.match(r"^[a-z]+$", tok) or tok in ".,!?;:'\"-":
                        tokens.append(tok)
                line = f"{tag} " + " ".join(tokens)
                f.write(line + "\n")
                n_lines += 1
                n_chars += len(line)
            f.write("\n")  # blank line between conversations (engram paragraph separator)

    out_size = os.path.getsize(OUTPUT)
    print(f"  wrote {OUTPUT}  ({out_size / 1024:.1f} KB, {n_lines:,} lines)")


if __name__ == "__main__":
    main()
